"""
magi/config_validator.py — agent config drift validator.

Standalone validator analogous to magi/validate_schema.py, applying the
same alert-on-drift pattern to per-agent Letta config (temperature,
thinking budget, reasoning effort, model handle).

Background: 2026-05-20 BYOK verification reset Balthasar's
model_settings to provider defaults (temp 0.3→1.0, thinking budget
2048→1024, effort medium→None) when the revert step called
`c.agents.update(model=base_handle)` without `model_settings=`. The
drift persisted ~17 hours until the next `provision_agents.py` run
detected and corrected it. This validator catches such drift events
within one MAGI cycle (~4h) instead of waiting for the next manual
provisioning.

Used by:
  - scheduler.run_magi_cycle (start + end hooks)
  - operator CLI: `python -m magi.config_validator`

Failure mode: emit critical alert via database.insert_alert
(category='config_drift'), continue. Validator failure NEVER blocks a
trading cycle. The existing magi/notify.py:send_ntfy() push fires
automatically on critical alerts. insert_alert's 60-minute
per-(category, agent_id) dedup window prevents spam.

Source of truth: magi.provision_agents.AGENT_CONFIG. To declare the
correct config for an agent, edit AGENT_CONFIG. To change the
validator behavior for an agent, do not edit this file — edit the
declaration.
"""

import logging
import os
import sys

log = logging.getLogger(__name__)


def _check_one_agent(client, agent_key, desired_settings, registered_model):
    """Compare live Letta state for one agent vs. declared config.

    Returns a dict:
      {
        "agent_key":     str,
        "model_diff":    None or (live_model, registered_model),
        "settings_diff": list of (key, live_value, desired_value) tuples
                         from _model_settings_diff
        "letta_error":   None or str (transport / SDK error)
      }
    """
    from database import get_letta_agent_id
    from magi.provision_agents import _model_settings_diff

    letta_id = get_letta_agent_id(agent_key)
    if not letta_id:
        return {
            "agent_key":     agent_key,
            "model_diff":    None,
            "settings_diff": [],
            "letta_error":   f"agent {agent_key!r} not in agent_registry",
        }

    try:
        state = client.agents.retrieve(letta_id)
    except Exception as e:
        return {
            "agent_key":     agent_key,
            "model_diff":    None,
            "settings_diff": [],
            "letta_error":   f"agents.retrieve failed: {e!r}",
        }

    sd = state.model_dump()
    live_model = sd.get("model")
    live_ms = sd.get("model_settings") or {}

    model_diff = None
    if registered_model and live_model != registered_model:
        model_diff = (live_model, registered_model)

    settings_diff = _model_settings_diff(live_ms, desired_settings)

    return {
        "agent_key":     agent_key,
        "model_diff":    model_diff,
        "settings_diff": settings_diff,
        "letta_error":   None,
    }


def _format_diff_message(result):
    """Compose a single-line alert message describing the drift for one agent."""
    parts = []
    if result["letta_error"]:
        return f"{result['agent_key']}: {result['letta_error']}"
    if result["model_diff"]:
        live, registered = result["model_diff"]
        parts.append(f"model: live={live!r} registered={registered!r}")
    for key, live, desired in result["settings_diff"]:
        parts.append(f"{key}: live={live!r} desired={desired!r}")
    return f"{result['agent_key']}: " + " ; ".join(parts)


def _letta_client():
    """Build a Letta client from LETTA_API_KEY (loaded via .env)."""
    # Match the env-loading pattern used elsewhere in the codebase.
    from pathlib import Path
    repo_root = Path(__file__).resolve().parent.parent
    env_path = repo_root / ".env"
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            if k and v and k not in os.environ:
                os.environ[k] = v
    api_key = os.environ.get("LETTA_API_KEY")
    if not api_key:
        raise RuntimeError("LETTA_API_KEY not in environment (or .env)")
    from letta_client import Letta
    return Letta(api_key=api_key)


def validate_agent_configs():
    """Validate every agent in AGENT_CONFIG against its live Letta state.

    Returns a list of per-agent result dicts. Caller decides whether to
    emit alerts (see alert_on_config_drift) or just inspect results
    (CLI / operator use).
    """
    from magi.provision_agents import AGENT_CONFIG, AGENT_SPECS

    client = _letta_client()
    # Build agent_key -> registered model map from AGENT_SPECS so the
    # validator catches "registered model has been overwritten on Letta
    # side" as well as model_settings drift.
    registered_by_key = {spec["agent_id"]: spec["model"] for spec in AGENT_SPECS}

    results = []
    for agent_key, desired in AGENT_CONFIG.items():
        registered_model = registered_by_key.get(agent_key)
        result = _check_one_agent(client, agent_key, desired, registered_model)
        results.append(result)
    return results


def alert_on_config_drift():
    """Run validation and, on any drift, write a critical alert per
    affected agent. Returns the number of agents with drift (0 = clean).

    Designed to be cheap to call repeatedly: alert dedup is handled by
    database.insert_alert's 60-minute per-(category, agent_id) window.
    """
    try:
        results = validate_agent_configs()
    except Exception as e:
        log.warning("config_validator failed to run: %s", e)
        return 0

    drift_count = 0
    for result in results:
        clean = (
            result["letta_error"] is None
            and result["model_diff"] is None
            and not result["settings_diff"]
        )
        if clean:
            continue
        drift_count += 1
        msg = _format_diff_message(result)
        try:
            from database import insert_alert
            insert_alert(
                severity="critical",
                category="config_drift",
                agent_id=result["agent_key"],
                message=msg,
            )
            log.warning("config drift detected for %s: %s",
                        result["agent_key"], msg)
        except Exception as e:
            log.error("failed to write config_drift alert for %s: %s",
                      result["agent_key"], e)
    return drift_count


# ----------------------------------------------------------------------
# CLI entry point
# ----------------------------------------------------------------------

def main():
    """Standalone CLI. Exits 0 on PASS, 1 on any drift, 2 on internal failure."""
    try:
        results = validate_agent_configs()
    except Exception as e:
        print(f"[FATAL] validator failed: {e!r}", file=sys.stderr)
        return 2

    from magi.provision_agents import AGENT_CONFIG
    print(f"magi/config_validator.py — checking {len(AGENT_CONFIG)} agents\n")

    any_drift = False
    for result in results:
        agent_key = result["agent_key"]
        if result["letta_error"]:
            print(f"[ERR] {agent_key}: {result['letta_error']}")
            any_drift = True
            continue
        if result["model_diff"] is None and not result["settings_diff"]:
            print(f"[OK]  {agent_key}: model + model_settings match AGENT_CONFIG")
            continue
        any_drift = True
        if result["model_diff"]:
            live, registered = result["model_diff"]
            print(f"[ERR] {agent_key}: model handle drift — "
                  f"live={live!r} registered={registered!r}")
        for key, live, desired in result["settings_diff"]:
            print(f"[ERR] {agent_key}: model_settings.{key} — "
                  f"live={live!r} desired={desired!r}")

    print("-" * 72)
    if any_drift:
        print("SUMMARY: at least one agent drifted — FAIL")
        return 1
    print("SUMMARY: all agents match AGENT_CONFIG — PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
