# =============================================================
# MAGI SYSTEM — PROMPT LOADER
# Each agent prompt lives in its own file.
# Edit melchior_prompt.txt, balthasar_prompt.txt, casper_prompt.txt
# Do NOT edit this file for prompt changes.
# =============================================================

import os

_dir = os.path.dirname(os.path.abspath(__file__))

def _load(filename):
    with open(os.path.join(_dir, filename), "r") as f:
        return f.read()

MELCHIOR_SYSTEM  = _load("melchior_prompt.txt")
BALTHASAR_SYSTEM = _load("balthasar_prompt.txt")
CASPER_SYSTEM    = _load("casper_prompt.txt")
