"""Casper persona-instruction optimization package for `adk optimize`.

`adk optimize` loads `root_agent` from the `agent` submodule of this package.
The custom eval metric lives in `metrics.py`; the evalset is generated by
`build_evalset.py`. Nothing here touches the live magi council path — it only
reads casper.md (via magi.agents.personas.load_persona) and RegimeVote.
"""

from . import agent  # noqa: F401  (exposes agent.root_agent for `adk optimize`)
