#!/usr/bin/env bash
# run_all.sh — execute all four analysis scripts in sequence, capture
# combined stdout to a single log, and emit a summary markdown file
# distilling the key findings. READ-ONLY on observer.db.
#
# Usage: bash /root/xrp_grid/analysis/run_all.sh

set -u

ANALYSIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="${ANALYSIS_DIR}/output"
PYTHON="/root/xrp_grid/venv/bin/python"
TS="$(date -u +%Y%m%dT%H%M%S)"
LOG="${OUT_DIR}/run_${TS}.log"
SUMMARY="${OUT_DIR}/SUMMARY_${TS}.md"

mkdir -p "${OUT_DIR}"

# DB read-only sanity guard — record the row count before and after.
ROW_BEFORE=$(sqlite3 /root/xrp_grid/observer.db "SELECT COUNT(*) FROM debate_records;" 2>/dev/null)

{
  echo "=========================================="
  echo "Analysis run ${TS}"
  echo "debate_records row count BEFORE: ${ROW_BEFORE}"
  echo "=========================================="
  echo

  for script in replay_predicate_gates.py forecast_quality.py \
                replay_weighted_consensus.py oneshot_doctrine.py; do
    echo "=========================================="
    echo ">>> ${script}"
    echo "=========================================="
    "${PYTHON}" "${ANALYSIS_DIR}/${script}"
    rc=$?
    echo
    echo "--- exit status: ${rc}"
    echo
    if [ "${rc}" -ne 0 ]; then
      echo "ABORT: ${script} exited non-zero. See log for details." >&2
      exit "${rc}"
    fi
  done

  ROW_AFTER=$(sqlite3 /root/xrp_grid/observer.db "SELECT COUNT(*) FROM debate_records;" 2>/dev/null)
  echo "debate_records row count AFTER:  ${ROW_AFTER}"
  if [ "${ROW_BEFORE}" != "${ROW_AFTER}" ]; then
    echo "ERROR: row count changed during analysis run — read-only invariant violated." >&2
    exit 3
  fi
  echo "Read-only invariant: PASSED (rows unchanged)."
} 2>&1 | tee "${LOG}"

# ----- Build the summary markdown by extracting key sections from the log ---
# Identify the freshest output files produced by this run.
PRED_CSV=$(ls -1t "${OUT_DIR}"/predicate_gates_*.csv 2>/dev/null | head -1)
FQ_CSV=$(ls -1t "${OUT_DIR}"/forecast_quality_*.csv 2>/dev/null | head -1)
WC_CSV=$(ls -1t "${OUT_DIR}"/weighted_consensus_replay_*.csv 2>/dev/null | head -1)
DOC_MD=$(ls -1t "${OUT_DIR}"/doctrine_generation_*.md 2>/dev/null | head -1)

{
  echo "# MAGI Analysis Summary"
  echo
  echo "Run timestamp: \`${TS}\` UTC"
  echo "Generated by \`analysis/run_all.sh\`"
  echo
  echo "Source data: \`observer.db\` (read-only). \
debate_records row count was ${ROW_BEFORE} both before and after this run."
  echo
  echo "---"
  echo
  echo "## 1. Predicate gate replay (Script 1)"
  echo
  echo "CSV: \`${PRED_CSV##*/}\`"
  echo
  echo '```'
  awk '/>>> replay_predicate_gates.py/{flag=1;next} />>> forecast_quality.py/{flag=0} flag' "${LOG}" \
    | sed -n '/^# Predicate gate replay/,/^--- exit status/p' \
    | sed '/^--- exit status/d'
  echo '```'
  echo
  echo "## 2. Per-agent forecast quality (Script 2)"
  echo
  echo "CSV: \`${FQ_CSV##*/}\`"
  echo
  echo '```'
  awk '/>>> forecast_quality.py/{flag=1;next} />>> replay_weighted_consensus.py/{flag=0} flag' "${LOG}" \
    | sed -n '/^# Per-agent forecast quality/,/^--- exit status/p' \
    | sed '/^--- exit status/d'
  echo '```'
  echo
  echo "## 3. Weighted consensus replay (Script 3)"
  echo
  echo "CSV: \`${WC_CSV##*/}\`"
  echo
  echo '```'
  awk '/>>> replay_weighted_consensus.py/{flag=1;next} />>> oneshot_doctrine.py/{flag=0} flag' "${LOG}" \
    | sed -n '/^# Weighted consensus replay/,/^--- exit status/p' \
    | sed '/^--- exit status/d'
  echo '```'
  echo
  echo "## 4. Doctrine generation (Script 4 — single Haiku 4.5 call)"
  echo
  echo "Output: \`${DOC_MD##*/}\`"
  echo
  echo '```'
  awk '/>>> oneshot_doctrine.py/{flag=1;next} /^debate_records row count AFTER/{flag=0} flag' "${LOG}" \
    | sed -n '/^# Doctrine generation/,/^--- exit status/p' \
    | sed '/^--- exit status/d'
  echo '```'
  echo
  echo "### Doctrine body"
  echo
  if [ -n "${DOC_MD}" ] && [ -f "${DOC_MD}" ]; then
    sed -n '/^---$/,$ p' "${DOC_MD}" | sed '1d'
  else
    echo "(no doctrine output file found)"
  fi
  echo
  echo "---"
  echo
  echo "## Caveats"
  echo
  echo "- Sample size (post-anchor cycles since 2026-05-19T13:04:17) is small. "
  echo "  All metrics are directional, not statistically significant. Re-run as "
  echo "  more cycles accumulate."
  echo "- Predicate replay's legacy CONFLICT_MATRIX evaluation is restricted to "
  echo "  the action-incompatibility rules (TIGHTEN+TRENDING, WIDEN+PAUSE_*, "
  echo "  HALT-high-conv). Grid-state-aware rules require per-cycle open_orders "
  echo "  snapshots not stored in debate_records."
  echo "- Weighted consensus PnL comparisons are indirect — true counterfactuals "
  echo "  cannot be observed. The differing-rate is the primary signal; PnL "
  echo "  deltas are informational only."
  echo "- Doctrine generation is a single-call viability test, not a curated "
  echo "  rule proposal. Treat the output as a starting point for operator review."
} > "${SUMMARY}"

echo
echo "Summary written to ${SUMMARY}"
